[package]
name = "stainless_pm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.37"
aes-gcm = "0.9.4"
argon2 = "0.3.1"
rand = "0.8.4"
flate2 = "1.0.22"