[package]
name = "stainless_pm"
version = "0.1.0"
edition = "2018"
author = "flareflo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.37"
aes-gcm = "0.9.4"